CMPUT301F23T08/HouseHomey

- doc/team.txt
Added CCID and Github Username
> Added my info to team.txt

- doc/team.txt
> Added antonio's info

- doc/team.txt
> Added Sami's info

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/househomey/AddItemFragment.java
- app/src/main/java/com/example/househomey/HomeFragment.java
- app/src/main/java/com/example/househomey/ItemList.java
- app/src/main/java/com/example/househomey/MainActivity.java
- app/src/main/java/com/example/househomey/User.java
- app/src/main/res/drawable/baseline_add_24.xml
- app/src/main/res/drawable/baseline_barcode_scanner_24.xml
- app/src/main/res/drawable/baseline_calendar_month_24.xml
- app/src/main/res/drawable/baseline_check_24.xml
- app/src/main/res/drawable/baseline_chevron_left_24.xml
- app/src/main/res/drawable/baseline_home_24.xml
- app/src/main/res/drawable/baseline_person_24.xml
- app/src/main/res/drawable/rounded_background.xml
- app/src/main/res/drawable/text_input_style.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_add_item.xml
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/layout/list_item.xml
- app/src/main/res/menu/navbar.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/themes.xml
Hoping to merge this PR a little early so that you all have reference into how to use the Material Design 3 components, and how I have overwritten some of the default colors in XML to match our files.
This PR includes:
- all colors used in Figma design (see `res/colors`)
- some overwritten TextInput and Menu XML styles for Material Design 3
- all the code for the Add Item page issue, other than form input validation. Features a calendar widget DatePicker for dates
> Base app theme/color code and Start of Add Item UI

- app/src/main/java/com/example/househomey/HomeFragment.java
- app/src/main/java/com/example/househomey/Item.java
- app/src/main/java/com/example/househomey/ItemAdapter.java
- app/src/main/java/com/example/househomey/MainActivity.java
- app/src/main/java/com/example/househomey/ViewItemFragment.java
- app/src/main/res/layout/fragment_view_item.xml
- app/src/main/res/layout/list_item.xml
- app/src/main/res/values/colors.xml
- created fragment for viewing details of an item (ViewItemFragment.java + fragment_view_item.xml)
- fragment can be accessed by clicking on viewItemButton (initialized in ItemAdapter id: _action_view_)
- sent details of item from ItemAdapter to ViewItemFragment
- added more getters for Item class
> Created View Item fragment

- .github/pull_request_template.md
Added a PR template
Here is how the template looks:
> chore: added pr template

- app/src/main/java/com/example/househomey/filter/model/DateFilter.java
- app/src/main/java/com/example/househomey/filter/ui/DateFilterFragment.java
- app/src/main/java/com/example/househomey/filter/ui/FilterFragment.java
- app/src/main/java/com/example/househomey/form/ItemFormFragment.java
- app/src/main/java/com/example/househomey/utils/FragmentUtils.java
- app/src/main/res/layout/fragment_filter_by_dates.xml
- Enables filtering out of list items outside a lower bounded start date and upper bounded end date
This PR addresses: (https://github.com/CMPUT301F23T08/HouseHomey/issues/28)
> Create Date Filter

- app/src/main/java/com/example/househomey/HomeFragment.java
- app/src/main/java/com/example/househomey/filter/ui/KeywordFilterFragment.java
> Changes reccomended for the keyword filter

- app/src/main/java/com/example/househomey/HomeFragment.java
- app/src/main/java/com/example/househomey/ItemAdapter.java
- app/src/main/java/com/example/househomey/filter/model/DateFilter.java
- app/src/main/java/com/example/househomey/filter/ui/DateFilterFragment.java
- app/src/main/java/com/example/househomey/filter/ui/FilterFragment.java
- app/src/main/java/com/example/househomey/form/EditItemFragment.java
- app/src/main/java/com/example/househomey/form/ItemFormFragment.java
- app/src/main/java/com/example/househomey/utils/FragmentUtils.java
- app/src/test/java/com/example/househomey/ItemTest.java
Added functionality to DATE FILTER
- Enabled resetting of date filter
- populated start date and end date fields with the previous date filter
This PR addresses: #61
> Added Reset functionality and autofill previous filter (DATE FILTER)

- app/src/androidTest/java/com/example/househomey/MakeFilterFragmentTest.java
- app/src/test/java/com/example/househomey/MakeFilterTest.java
- Add espresso tests for make filter fragment
- Add unit tests for make filter model
This PR addresses: https://github.com/CMPUT301F23T08/HouseHomey/issues/27
> test: implement tests for make filter and it's fragment

- app/src/androidTest/java/com/example/househomey/ViewItemFragmentTest.java
> Greatest espresso Tests ever

- app/src/androidTest/java/com/example/househomey/KeywordFragmentTest.java
- app/src/test/java/com/example/househomey/KeywordFilterTest.java
> Added testing for fitler logic

- app/src/androidTest/java/com/example/househomey/DateFilterFragmentTest.java
- app/src/androidTest/java/com/example/househomey/testUtils/TestHelpers.java
- Adds UI espresso tests for the date range
This PR addresses: https://github.com/CMPUT301F23T08/HouseHomey/issues/28
> UI tests for date range fragment

- app/src/test/java/com/example/househomey/DateFilterTest.java
- Unit tests for date filter
This PR addresses: #51
> Added unit tests for date filter

- app/src/main/java/com/example/househomey/form/ItemFormFragment.java
- app/src/main/java/com/example/househomey/form/PhotoAdapter.java
- app/src/main/java/com/example/househomey/utils/FragmentUtils.java
- app/src/main/res/drawable/baseline_close_24.xml
- app/src/main/res/drawable/delete_button.xml
- app/src/main/res/layout/add_photo_button.xml
- app/src/main/res/layout/gallery_photo.xml
- app/src/main/res/layout/gallery_photo_with_delete.xml
- allows a user to delete photos added to the Add/Edit Item pages
- only deletes existing photos in Firebase when Edit is confirmed
This PR addresses: #19
> [US 04.03.01] Delete photos attached to item

- test_data/README.md
- test_data/espresso_test_data.json
- test_data/fb_batch_write.py
- test_data/requirements.txt
See the README.md in this commit for context.
> Add Python script/instructions for writing multiple Items to a Firestore User

- app/src/androidTest/java/com/example/househomey/SelectDeleteTest.java
- Adds UI espresso tests for selecting and deleting items from the list
This PR addresses: [#22](https://github.com/CMPUT301F23T08/HouseHomey/issues/22)
> select delete ui test

- app/src/main/java/com/example/househomey/SelectFragment.java
- app/src/main/java/com/example/househomey/tags/TagFragment.java
- app/src/main/java/com/example/househomey/utils/FragmentUtils.java
- app/src/main/res/drawable/tag_chip.xml
> Select and delete tags

- app/src/main/java/com/example/househomey/HomeFragment.java
- app/src/main/java/com/example/househomey/filter/model/Filter.java
- app/src/main/java/com/example/househomey/filter/model/FilterCallback.java
- app/src/main/java/com/example/househomey/filter/model/KeywordFilter.java
- app/src/main/java/com/example/househomey/filter/model/MakeFilter.java
- app/src/main/java/com/example/househomey/filter/ui/DateFilterFragment.java
- app/src/main/java/com/example/househomey/filter/ui/FilterFragment.java
- app/src/main/java/com/example/househomey/filter/ui/KeywordFilterFragment.java
- app/src/main/java/com/example/househomey/filter/ui/MakeFilterFragment.java
- app/src/main/java/com/example/househomey/filter/ui/TagFilterFragment.java
> Bundle Refactoring

- app/src/main/java/com/example/househomey/ViewItemFragment.java
- app/src/main/res/layout/fragment_view_item.xml
- allows user to view tags linked to an item on the view item page
- allows the user to delete the item's involvement with the tag from the view item page.
This PR addresses: #97
> View item Tags

- app/src/main/java/com/example/househomey/SelectFragment.java
- app/src/main/res/layout/base_toolbar.xml
- app/src/main/res/layout/select_toolbar.xml
- app/src/main/res/values/strings.xml
> BUG FIX select scrolling

- app/src/main/java/com/example/househomey/HomeFragment.java
- app/src/main/java/com/example/househomey/Item.java
- app/src/main/java/com/example/househomey/sort/TagComparator.java
- app/src/main/java/com/example/househomey/tags/Tag.java
- app/src/main/res/menu/sort.xml
> Sorting by tags

- app/src/main/java/com/example/househomey/form/AddItemFragment.java
- app/src/main/java/com/example/househomey/form/ItemFormFragment.java
> [BUGFIX] remove extra space when textfield error cleared
